server:
  port: 8087
  session:
  cookie:
    name: sessionid
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true&useAffectedRows=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: "classpath*:com/example/LqcSpringBoot/mapperXml/*.xml"
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl